# Generated by Django 2.1.9 on 2020-09-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200921_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('CustomerID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=100)),
                ('ContactName', models.CharField(max_length=100)),
                ('ContactTitle', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('OrderID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('CustomerID', models.CharField(max_length=10)),
                ('EmployeeID', models.CharField(max_length=100)),
                ('OrderDate', models.CharField(max_length=100)),
                ('RequiredDate', models.CharField(max_length=100)),
                ('ShippedDate', models.CharField(max_length=100)),
                ('ShipVia', models.CharField(max_length=100)),
                ('Freight', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
    ]
