# Generated by Django 2.1.9 on 2020-09-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customers_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Host', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Database', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'DBData',
            },
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
